<?php

namespace Acme\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRepository extends EntityRepository
{
	public function getAllClients(){
		
    	return $this->findBy(array(), array('clientId' => 'ASC'));
    }
}
