<?php

namespace Acme\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoicesRepository extends EntityRepository
{
	public function getAllInvoicesByClients($clientId, $datefilter){
		 
		if($datefilter == "1") {
			
			$sql = 'SELECT * FROM Invoices 
					INNER JOIN InvoiceLineItems ON Invoices.invoice_num = InvoiceLineItems.invoice_num 
					INNER JOIN Products ON InvoiceLineItems.product_id = Products.product_id
					WHERE Invoices.client_id LIKE :id AND Invoices.invoice_date BETWEEN "'.date('Y').'-'.date('m').'-01'.'" AND "'.date('Y-m-j').'"';
					
		} 
		else if($datefilter == "2") {
			
			$sql = 'SELECT * FROM Invoices 
					INNER JOIN InvoiceLineItems ON Invoices.invoice_num = InvoiceLineItems.invoice_num 
					INNER JOIN Products ON InvoiceLineItems.product_id = Products.product_id
					WHERE Invoices.client_id LIKE :id AND Invoices.invoice_date BETWEEN "'.date('Y').'-01'.'-01'.'" AND "'.date('Y').'-12'.'-31'.'"';
		}
		else if($datefilter == "3") {
			$dty = date('Y');
			$dtly = $dty-1;
			
			$dtlastyear = $dtly."-01"."-01";
			
			$lastmonthtodate = '';
			$sql = 'SELECT * FROM Invoices 
					INNER JOIN InvoiceLineItems ON Invoices.invoice_num = InvoiceLineItems.invoice_num 
					INNER JOIN Products ON InvoiceLineItems.product_id = Products.product_id
					WHERE Invoices.client_id LIKE :id AND Invoices.invoice_date BETWEEN "'.$dtlastyear.'" AND "'.$dtly.'-12'.'-31'.'"';
		} 
		else {
			$sql = 'SELECT * FROM Invoices 
					INNER JOIN InvoiceLineItems ON Invoices.invoice_num = InvoiceLineItems.invoice_num 
					INNER JOIN Products ON InvoiceLineItems.product_id = Products.product_id
					WHERE Invoices.client_id LIKE :id AND Invoices.invoice_date';
		}
		$params = array(
		'id' => '%'.$clientId.'%',
		);

	return $this->getEntityManager()->getConnection()->executeQuery($sql, $params)->fetchAll();
	}
}
