<?php

namespace Acme\Bundle\TestBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductsRepository extends EntityRepository
{
	
	//repository function to fetch data relative in invoice and invoicelineitems tables.  
	public function getAllProducts(){
		
		$sql = 'SELECT * FROM Products';

	return $this->getEntityManager()->getConnection()->executeQuery($sql)->fetchAll();
	}
}
